import type { Metadata } from "next";
import { geistMono, geistSans } from "@/shared/fonts";
import "@/app/scss/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
