import type { Metadata } from "next";
import { geistMono, geistSans } from "@/shared/fonts";
import "@/app/scss/styles.scss";
import { Container } from "@/shared/ui/container";
import { Header } from "@/widgets/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
